export enum AvailabilityEnum {
  AVAILABLE = 'AVAILABLE',
  CHARGING = 'CHARGING',
  BLOCKED = 'BLOCKED',
  RESERVED = 'RESERVED',
  OUTOFORDER = 'OUTOFORDER',
  UNAVAILABLE = 'UNAVAILABLE',
  UNKNOWN = 'UNKNOWN',
  PLANNED = 'PLANNED',
  REMOVED = 'REMOVED',
  INOPERATIVE = 'INOPERATIVE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}
