export const getPossibleCategory = (address: string, poiName: string) => {
  if (poiName) {
    return null;
  }

  if (!address) {
    return null;
  }

  const addressArray = address.split(',');

  if (addressArray.length < 2) {
    if (TOMTOM_POI_CATEGORIES.includes(address.toLowerCase())) {
      return address;
    }

    return null;
  }

  const [possibleCategoryInput] = addressArray;
  const sanitizedInput = possibleCategoryInput
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim()
    .toLowerCase();
  const tomtomCategory = TOMTOM_POI_CATEGORIES.find((category) => {
    if (category === sanitizedInput) {
      return true;
    }

    if (
      longestCommonSubstring(category, possibleCategoryInput.toLowerCase()) ===
      category
    ) {
      return true;
    }

    return false;
  });

  if (tomtomCategory) {
    return possibleCategoryInput;
  }

  return null;
};

export const getPossibleChargePointPoiCategory = (category: string) => {
  if (!category) {
    return null;
  }

  const addressArray = category.split(',');

  if (addressArray.length < 2) {
    if (CHARGE_POINT_SEARCH_CATEGORIES.includes(category.toLowerCase())) {
      return category;
    }

    return null;
  }

  const [possibleCategoryInput] = addressArray;
  const sanitizedInput = possibleCategoryInput
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim()
    .toLowerCase();
  const matchedCategory = CHARGE_POINT_SEARCH_CATEGORIES.find((category) => {
    if (category === sanitizedInput) {
      return true;
    }

    if (
      longestCommonSubstring(category, possibleCategoryInput.toLowerCase()) ===
      category
    ) {
      return true;
    }

    return false;
  });

  if (matchedCategory) {
    return possibleCategoryInput;
  }

  return null;
};

export const getPossiblePoiSearchCategory = (category: string) => {
  if (!category) {
    return null;
  }

  const addressArray = category.split(',');

  if (addressArray.length < 2) {
    if (POI_SEARCH_BASED_ON_CATEGORIES.includes(category.toLowerCase())) {
      return category;
    }

    return null;
  }

  const [possibleCategoryInput] = addressArray;
  const sanitizedInput = possibleCategoryInput
    .replace(/[^a-zA-Z0-9]/g, '')
    .trim()
    .toLowerCase();
  const matchedCategory = POI_SEARCH_BASED_ON_CATEGORIES.find((category) => {
    if (category === sanitizedInput) {
      return true;
    }

    if (
      longestCommonSubstring(category, possibleCategoryInput.toLowerCase()) ===
      category
    ) {
      return true;
    }

    return false;
  });

  if (matchedCategory) {
    return possibleCategoryInput;
  }

  return null;
};

export const longestCommonSubstring = (str1: string, str2: string) => {
  let longestSubstring = '';

  for (let i = 0; i < str1.length; i++) {
    for (let j = 0; j < str2.length; j++) {
      let substring = '';
      let x = i;
      let y = j;

      while (x < str1.length && y < str2.length && str1[x] === str2[y]) {
        substring += str1[x];
        x++;
        y++;
      }

      if (substring.length > longestSubstring.length) {
        longestSubstring = substring;
      }
    }
  }

  return longestSubstring;
};

export const TOMTOM_POI_CATEGORIES = [
  'administrative area',
  'adventure sports venue',
  'afghan',
  'african',
  'agriculture',
  'airfield',
  'airline',
  'airport',
  'algerian',
  'american',
  'amphitheater',
  'amusement park',
  'anabranch',
  'animal services',
  'animal shelter',
  'antique/art',
  'aquatic zoo marine park',
  'arabian',
  'arboreta botanical gardens',
  'arch',
  'argentinean',
  'armenian',
  'art school',
  'art gallery',
  'ashram',
  'asian',
  'asylum',
  'australian',
  'austrian',
  'automatic teller machine',
  'automotive dealer',
  'bakery',
  'balloonport',
  'bank',
  'mall',
  'bar',
  'basque',
  'beach',
  'beach club',
  'beauty salon',
  'bed breakfast guest houses',
  'belgian',
  'bistro',
  'blood bank',
  'boat launching ramp',
  'bolivian',
  'book shops',
  'bosnian',
  'bowling',
  'brazilian',
  'brewery',
  'bridge',
  'british',
  'buffet',
  'bulgarian',
  'burmese',
  'bus station',
  'bus stop',
  'cabaret',
  'café',
  'café/pub',
  'californian',
  'cambodian',
  'camping ground',
  'canadian',
  'car wash',
  'caribbean',
  'casino',
  'castle',
  'cave',
  'cemetery',
  'chalet',
  'child care facility',
  'chilean',
  'chinese',
  'christmas/holiday store',
  'church',
  'cinema',
  'cleaning services',
  'clinic',
  'clothing',
  'club association',
  'coast guard station',
  'cocktail bar',
  'coffee shop',
  'college',
  'college/university',
  'colombian',
  'comedy club',
  'community center',
  'computer data services',
  'concert hall',
  'condominium complex',
  'construction material equipment',
  'convenience stores',
  'grocery store',
  'convent',
  'coral reef',
  'corsican',
  'cottage',
  'courthouse',
  'cove',
  'creole-cajun',
  'cricket ground',
  'crêperie',
  'cuban',
  'culinary school',
  'cultural center',
  'customs post',
  'cypriot',
  'czech',
  'dam',
  'dance studio school',
  'danish',
  'delicatessen',
  'dentist',
  'department store',
  'diplomatic facility',
  'discotheque',
  'dispensary',
  'dock',
  'dockyard',
  'doctor',
  'dominican',
  'dongbei',
  'doughnuts',
  'drive-in cinema',
  'driving school',
  'drug store',
  'dry cleaners',
  'dutch',
  'egyptian',
  'electronics',
  'embassy',
  'emergency medical service',
  'english',
  'entertainment',
  'equipment rental',
  'erotic',
  'ethiopian',
  'exhibition convention center',
  'factory',
  'factory outlet',
  'fairground',
  'farm',
  'fast food',
  'ferry',
  'ferry terminal',
  'filipino',
  'finnish',
  'fire station/brigade',
  'fishing area',
  'fitness club center',
  'florists',
  'flying club',
  'forest',
  'fort',
  'foundry',
  'free trade zone',
  'french',
  'fuel depot',
  'funeral service mortuaries',
  'furniture/home furnishings',
  'garden',
  'general car repair servicing',
  'general practitioner',
  'geographic feature',
  'german',
  'geyser',
  'gym',
  'gifts, cards, novelties souvenirs',
  'glacier',
  'golf course',
  'gorge',
  'government office',
  'greek',
  'grill',
  'guangdong',
  'guest house',
  'gurudwara',
  'hairdressers',
  'barbers',
  'barbershop',
  'hamburgers',
  'harbor',
  'hardware',
  'hawaiian',
  'health care service',
  'helipad/helicopter landing',
  'heliport',
  'hermitage',
  'high school',
  'hill',
  'historic site',
  'hockey club',
  'holiday rental',
  'home appliance repair',
  'horse racing',
  'hospital',
  'polyclinic',
  'hostel',
  'hot pot',
  'hotel',
  'hotel/motel',
  'hunan',
  'hungarian',
  'hunting reserve',
  'ice cream',
  'ice hockey',
  'ice skating rink',
  'import/export distribution',
  'important tourist attraction',
  'indian',
  'indonesian',
  'industrial building',
  'insurance',
  'internet café',
  'investment advisors',
  'iranian',
  'irish',
  'island',
  'israeli',
  'italian',
  'jamaican',
  'japanese',
  'jazz club',
  'jetty',
  'jewelry, clocks watches',
  'jewish',
  'junior college/community college',
  'karaoke club',
  'korean',
  'kosher',
  'lagoon',
  'language school',
  'latin american',
  'laundry',
  'lebanese',
  'legal services',
  'leprosarium',
  'library',
  'lighthouse',
  'lottery shop',
  'luxembourgian',
  'maghrib',
  'mail/package/freight delivery',
  'maltese',
  'manufacturing facility',
  'marina',
  'market',
  'mauritian',
  'mausoleum/grave',
  'medical center',
  'mediterranean',
  'memorial',
  'metro station',
  'mexican',
  'middle eastern',
  'middle school',
  'military installation',
  'mineral/hot springs',
  'monastery',
  'mongolian',
  'monument',
  'moroccan',
  'mosque',
  'motel',
  'motorcycle repair',
  'motoring organization office',
  'mountain pass',
  'mountain peak',
  'moving storage',
  'museum',
  'music center',
  'mussels',
  'nail salon',
  'native reservation',
  'natural attraction',
  'nature reserve',
  'naval base',
  'nepalese',
  'nightlife',
  'non governmental organization (NGO)',
  'norwegian',
  'oasis',
  'observation point',
  'observatory',
  'office building',
  'open parking area',
  'opera house',
  'opticians',
  'oriental',
  'pagoda',
  'pakistani',
  'palace',
  'park',
  'parking',
  'pawn shop',
  'personal care facility',
  'peruvian',
  'pet supplies',
  'petrol station',
  'pharmacy',
  'photo lab/development',
  'photocopy',
  'picnic area',
  'pier',
  'pizza',
  'place of worship',
  'playground',
  'planetarium',
  'police station',
  'polish',
  'polynesian',
  'port',
  'portuguese',
  'post office',
  'pre school',
  'primary school',
  'prison',
  'promenade',
  'provençal',
  'pub',
  'public restroom',
  'public transport stop',
  'pyramid',
  'quarry',
  'race track',
  'railway station',
  'recreational',
  'recycling shop',
  'religious center',
  'religious site',
  'rent-a-car facility',
  'repair shops',
  'research facility',
  'reservation',
  'reservoir',
  'resort',
  'rest area',
  'restaurant',
  'retirement community',
  'retreat',
  'river crossing',
  'road rescue',
  'rock climbing',
  'rugby ground',
  'rumanian',
  'russian',
  'salad bar',
  'sanatorium',
  'sauna, solarium massage',
  'savoyan',
  'scandinavian',
  'school',
  'scottish',
  'seafood',
  'senior high school',
  'service station',
  'shandong',
  'shanghai',
  'shop',
  'shopping center',
  'sichuan',
  'sicilian',
  'ski resort',
  'slavic',
  'slovak',
  'spa',
  'spanish',
  'special school',
  'specialty foods',
  'sport school',
  'sports center',
  'sports equipment clothing',
  'squash court',
  'stadium',
  'statue',
  'steak house',
  'stock exchange',
  'store',
  'sudanese',
  'supermarket',
  'surinamese',
  'sushi',
  'swedish',
  'swimming pool',
  'swiss',
  'synagogue',
  'syrian',
  'tailor shop',
  'taiwanese',
  'tapas bar',
  'taxi stand',
  'tea house',
  'technical school',
  'temple',
  'tennis court',
  'teppanyakki',
  'thai',
  'theater',
  'tibetan',
  'toilet',
  'tourist information office',
  'toys games',
  'tram stop',
  'truck repair service',
  'truck stop',
  'tunisian',
  'tunnel',
  'turkish',
  'united states government establishment',
  'university',
  'uruguayan',
  'vegetarian',
  'vegan',
  'venezuelan',
  'veterinarian',
  'vietnamese',
  'water sport',
  'wedding services',
  'welfare organization',
  'welsh',
  'western continental',
  'wholesale clubs',
  'wildlife park',
  'wildlife reserve',
  'wine bar',
  'winery',
  'yoga studio',
  'yogurt/juice bar',
  'zoo',
];

const CHARGE_POINT_SEARCH_CATEGORIES = [
  'afghan',
  'african',
  'algerian',
  'american',
  'arabian',
  'argentinean',
  'armenian',
  'art gallery',
  'ashram',
  'asian',
  'australian',
  'austrian',
  'bakery',
  'bank',
  'mall',
  'bar',
  'beach',
  'beach club',
  'beauty salon',
  'bed breakfast guest houses',
  'belgian',
  'bolivian',
  'book shops',
  'bosnian',
  'bowling',
  'brazilian',
  'brewery',
  'british',
  'buffet',
  'bulgarian',
  'burmese',
  'café',
  'café/pub',
  'californian',
  'cambodian',
  'camping ground',
  'canadian',
  'caribbean',
  'casino',
  'chilean',
  'chinese',
  'cinema',
  'cleaning services',
  'clothing',
  'cocktail bar',
  'coffee shop',
  'colombian',
  'convenience stores',
  'grocery store',
  'corsican',
  'creole-cajun',
  'crêperie',
  'cuban',
  'cultural center',
  'cypriot',
  'czech',
  'danish',
  'delicatessen',
  'department store',
  'discotheque',
  'dominican',
  'dongbei',
  'doughnuts',
  'drug store',
  'dutch',
  'egyptian',
  'english',
  'entertainment',
  'ethiopian',
  'exhibition convention center',
  'fairground',
  'fast food',
  'filipino',
  'finnish',
  'fishing area',
  'fitness club center',
  'forest',
  'french',
  'garden',
  'german',
  'geyser',
  'gym',
  'gifts, cards, novelties souvenirs',
  'greek',
  'grill',
  'hairdressers',
  'barbers',
  'barbershop',
  'hamburgers',
  'hawaiian',
  'historic site',
  'hostel',
  'hot pot',
  'hotel',
  'hotel/motel',
  'hunan',
  'hungarian',
  'ice cream',
  'important tourist attraction',
  'indian',
  'indonesian',
  'internet café',
  'iranian',
  'irish',
  'israeli',
  'italian',
  'jamaican',
  'japanese',
  'jazz club',
  'jewish',
  'karaoke club',
  'korean',
  'kosher',
  'latin american',
  'lebanese',
  'luxembourgian',
  'maghrib',
  'maltese',
  'market',
  'mauritian',
  'mediterranean',
  'mexican',
  'mongolian',
  'monument',
  'moroccan',
  'mountain pass',
  'mountain peak',
  'native reservation',
  'natural attraction',
  'nepalese',
  'nightlife',
  'norwegian',
  'open parking area',
  'oriental',
  'pakistani',
  'palace',
  'park',
  'parking',
  'peruvian',
  'petrol station',
  'picnic area',
  'pizza',
  'place of worship',
  'playground',
  'polish',
  'polynesian',
  'portuguese',
  'pub',
  'rest area',
  'restaurant',
  'rumanian',
  'russian',
  'salad bar',
  'savoyan',
  'scandinavian',
  'scottish',
  'seafood',
  'service station',
  'shandong',
  'shanghai',
  'shop',
  'shopping center',
  'sichuan',
  'sicilian',
  'slavic',
  'slovak',
  'spanish',
  'steak house',
  'store',
  'sudanese',
  'supermarket',
  'surinamese',
  'sushi',
  'swedish',
  'swiss',
  'syrian',
  'taiwanese',
  'tapas bar',
  'taxi stand',
  'tea house',
  'teppanyakki',
  'thai',
  'tibetan',
  'toilet',
  'tram stop',
  'tunisian',
  'turkish',
  'uruguayan',
  'vegetarian',
  'vegan',
  'venezuelan',
  'vietnamese',
  'welsh',
  'western continental',
  'wine bar',
  'winery',
  'yogurt/juice bar',
];

const POI_SEARCH_BASED_ON_CATEGORIES = [
  'administrative area',
  'adventure sports venue',
  'agriculture',
  'airfield',
  'airline',
  'airport',
  'amphitheater',
  'amusement park',
  'anabranch',
  'animal services',
  'animal shelter',
  'antique/art',
  'aquatic zoo marine park',
  'arboreta botanical gardens',
  'arch',
  'art school',
  'asylum',
  'automatic teller machine',
  'automotive dealer',
  'balloonport',
  'basque',
  'bistro',
  'blood bank',
  'boat launching ramp',
  'bridge',
  'bus station',
  'bus stop',
  'cabaret',
  'car wash',
  'castle',
  'cave',
  'cemetery',
  'chalet',
  'child care facility',
  'christmas/holiday store',
  'church',
  'clinic',
  'club association',
  'coast guard station',
  'college',
  'college/university',
  'comedy club',
  'community center',
  'computer data services',
  'concert hall',
  'condominium complex',
  'construction material equipment',
  'convent',
  'coral reef',
  'cottage',
  'courthouse',
  'cove',
  'cricket ground',
  'culinary school',
  'customs post',
  'dam',
  'dance studio school',
  'dentist',
  'diplomatic facility',
  'dispensary',
  'dock',
  'dockyard',
  'doctor',
  'drive-in cinema',
  'driving school',
  'dry cleaners',
  'electronics',
  'embassy',
  'emergency medical service',
  'equipment rental',
  'erotic',
  'factory',
  'factory outlet',
  'farm',
  'ferry',
  'ferry terminal',
  'fire station/brigade',
  'florists',
  'flying club',
  'fort',
  'foundry',
  'free trade zone',
  'fuel depot',
  'funeral service mortuaries',
  'furniture/home furnishings',
  'general car repair servicing',
  'general practitioner',
  'geographic feature',
  'glacier',
  'golf course',
  'gorge',
  'government office',
  'guangdong',
  'guest house',
  'gurudwara',
  'harbor',
  'hardware',
  'health care service',
  'helipad/helicopter landing',
  'heliport',
  'hermitage',
  'high school',
  'hill',
  'hockey club',
  'holiday rental',
  'home appliance repair',
  'horse racing',
  'hospital',
  'polyclinic',
  'hunting reserve',
  'ice hockey',
  'ice skating rink',
  'import/export distribution',
  'industrial building',
  'insurance',
  'investment advisors',
  'island',
  'jetty',
  'jewelry, clocks watches',
  'junior college/community college',
  'lagoon',
  'language school',
  'laundry',
  'legal services',
  'leprosarium',
  'library',
  'lighthouse',
  'lottery shop',
  'mail/package/freight delivery',
  'manufacturing facility',
  'marina',
  'mausoleum/grave',
  'medical center',
  'memorial',
  'metro station',
  'middle eastern',
  'middle school',
  'military installation',
  'mineral/hot springs',
  'monastery',
  'mosque',
  'motel',
  'motorcycle repair',
  'motoring organization office',
  'moving storage',
  'museum',
  'music center',
  'mussels',
  'nail salon',
  'nature reserve',
  'naval base',
  'non governmental organization (NGO)',
  'oasis',
  'observation point',
  'observatory',
  'office building',
  'opera house',
  'opticians',
  'pagoda',
  'pawn shop',
  'personal care facility',
  'pet supplies',
  'pharmacy',
  'photo lab/development',
  'photocopy',
  'pier',
  'planetarium',
  'police station',
  'port',
  'post office',
  'pre school',
  'primary school',
  'prison',
  'promenade',
  'provençal',
  'public restroom',
  'public transport stop',
  'pyramid',
  'quarry',
  'race track',
  'railway station',
  'recreational',
  'recycling shop',
  'religious center',
  'religious site',
  'rent-a-car facility',
  'repair shops',
  'research facility',
  'reservation',
  'reservoir',
  'resort',
  'retirement community',
  'retreat',
  'river crossing',
  'road rescue',
  'rock climbing',
  'rugby ground',
  'sanatorium',
  'sauna, solarium massage',
  'school',
  'senior high school',
  'ski resort',
  'spa',
  'special school',
  'specialty foods',
  'sport school',
  'sports center',
  'sports equipment clothing',
  'squash court',
  'stadium',
  'statue',
  'stock exchange',
  'swimming pool',
  'synagogue',
  'tailor shop',
  'technical school',
  'temple',
  'tennis court',
  'theater',
  'tourist information office',
  'toys games',
  'truck repair service',
  'truck stop',
  'tunnel',
  'united states government establishment',
  'university',
  'veterinarian',
  'water sport',
  'wedding services',
  'welfare organization',
  'wholesale clubs',
  'wildlife park',
  'wildlife reserve',
  'yoga studio',
  'zoo',
];
