import {
  clusterLocationsTogether,
  getClusterSummarizer,
} from './clustering-locations-utils.service';

describe('Grouping of locations utils service', () => {
  describe('clusterLocationsTogether', () => {
    it('should group the locations together by walking distance', () => {
      const tomTomAPILocations = [
        {
          type: 'POI',
          id: '608eM5m11JoTURFCj8jwtQ',
          score: 2.5745270252,
          dist: 55.09987,
          info: 'search:ta:276009007570466-DE',
          poi: {
            name: 'Block House am Alexanderplatz',
            brands: [{ name: 'Block House' }],
            categorySet: [{ id: 7315045 }],
            url: 'www.block-house.de/restaurants/berlin/am-alexanderplatz',
            categories: ['restaurant', 'steak house'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'steak house' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'City Centre',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Germany',
            countryCodeISO3: 'DEU',
            freeformAddress:
              'Karl-Liebknecht-Straße, 10178 Berlin (Spandauer Vorstadt)',
            localName: 'Berlin',
          },
          position: { lat: 52.520476, lon: 13.405217 },
          viewport: {
            topLeftPoint: { lat: 52.52138, lon: 13.40374 },
            btmRightPoint: { lat: 52.51958, lon: 13.40669 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52041, lon: 13.40532 } },
          ],
        },
        {
          type: 'POI',
          id: '5B5J7-cFrvryHFIaMgm0vw',
          score: 2.5745265484,
          dist: 60.352925,
          info: 'search:ta:276006000353058-DE',
          poi: {
            name: 'Nordsee',
            phone: '+49 30 2426881',
            brands: [{ name: 'Nordsee' }],
            categorySet: [{ id: 7315043 }],
            url: 'www.nordsee.com',
            categories: ['restaurant', 'seafood'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'seafood' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '4',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520534, lon: 13.404743 },
          viewport: {
            topLeftPoint: { lat: 52.52143, lon: 13.40327 },
            btmRightPoint: { lat: 52.51963, lon: 13.40622 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52041, lon: 13.40449 } },
          ],
        },
        {
          type: 'POI',
          id: 'GAuX8kvkztlyv34oVaWJvg',
          score: 2.57452631,
          dist: 65.822336,
          info: 'search:ta:276009023845621-DE',
          poi: {
            name: 'Palm Beach',
            phone: '+49 30 97004660',
            categorySet: [{ id: 7315 }],
            url: 'www.palm-beach-berlin.de/',
            categories: ['restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ nameLocale: 'en-US', name: 'restaurant' }],
              },
            ],
          },
          address: {
            streetNumber: '4',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520561, lon: 13.404613 },
          viewport: {
            topLeftPoint: { lat: 52.52146, lon: 13.40314 },
            btmRightPoint: { lat: 52.51966, lon: 13.40609 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52046, lon: 13.40441 } },
          ],
        },
        {
          type: 'POI',
          id: 'zigfJ7TUD6cMFE9lTtUJnA',
          score: 2.5745260715,
          dist: 70.600674,
          info: 'search:ta:276006000353055-DE',
          poi: {
            name: 'Bäcker Wiedemann',
            phone: '+49 30 24358649',
            categorySet: [{ id: 7315015 }],
            url: 'www.baecker-wiedemann.de/',
            categories: ['fast food', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'fast food' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '5',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 5, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519888, lon: 13.403929 },
          viewport: {
            topLeftPoint: { lat: 52.52079, lon: 13.40245 },
            btmRightPoint: { lat: 52.51899, lon: 13.40541 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51974, lon: 13.40411 } },
          ],
        },
        {
          type: 'POI',
          id: 'R3cElgpewo3YTcP53ov-dw',
          score: 2.5745248795,
          dist: 94.528761,
          info: 'search:ta:276007000375164-DE',
          poi: {
            name: 'Dumpling House',
            phone: '+49 491 737561598',
            categorySet: [{ id: 7315012 }],
            url: 'www.dumplinghousebubbletee.de/',
            categories: ['chinese', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'chinese' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '3',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 3, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520451, lon: 13.403763 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40229 },
            btmRightPoint: { lat: 52.51955, lon: 13.40524 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52035, lon: 13.4042 } },
          ],
        },
        {
          type: 'POI',
          id: '3xDHz4IP8IEU75jXRVlJZQ',
          score: 2.5745248795,
          dist: 94.017488,
          info: 'search:ta:276009025204111-DE',
          poi: {
            name: 'Subway Berlin',
            phone: '+49 30 21230886',
            brands: [{ name: 'Subway' }],
            categorySet: [{ id: 7315042 }],
            url: 'www.subway.com/',
            categories: ['restaurant', 'sandwich'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'sandwich' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '3 d',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 3 d, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520393, lon: 13.403718 },
          viewport: {
            topLeftPoint: { lat: 52.52129, lon: 13.40224 },
            btmRightPoint: { lat: 52.51949, lon: 13.4052 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52059, lon: 13.40387 } },
          ],
        },
        {
          type: 'POI',
          id: 'zFp-Q6g83DU8VqpFkwLE6A',
          score: 2.5745244026,
          dist: 105.810452,
          info: 'search:ta:276009023456298-DE',
          poi: {
            name: 'Dean&david',
            phone: '+49 30 28873773',
            categorySet: [{ id: 7315048 }],
            url: 'deananddavid.de/standorte/berlin-karl-liebknecht-strasse/',
            categories: ['restaurant', 'thai'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'thai' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '7',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 7, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520794, lon: 13.405832 },
          viewport: {
            topLeftPoint: { lat: 52.52169, lon: 13.40435 },
            btmRightPoint: { lat: 52.51989, lon: 13.40731 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.5207, lon: 13.40588 } },
          ],
        },
        {
          type: 'POI',
          id: 'IP5gBRJeWy2COERFDd_zRQ',
          score: 2.5745244026,
          dist: 102.923579,
          info: 'search:ta:276007000503259-DE',
          poi: {
            name: 'Cloudeatery Food Hall',
            phone: '+49 160 99637485',
            categorySet: [{ id: 7315003 }],
            url: 'www.cloudeatery.kitchen/',
            categories: ['american', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'american' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '2',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 2, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52082, lon: 13.404228 },
          viewport: {
            topLeftPoint: { lat: 52.52172, lon: 13.40275 },
            btmRightPoint: { lat: 52.51992, lon: 13.40571 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52094, lon: 13.40374 } },
          ],
        },
        {
          type: 'POI',
          id: '1XygCESeA8jNQBHT24Q1Uw',
          score: 2.5745229721,
          dist: 121.640848,
          info: 'search:ta:276009023744134-DE',
          poi: {
            name: 'Shi-Mai Restaurant',
            phone: '+49 30 40054883',
            categorySet: [{ id: 7315148 }],
            url: 'www.shi-mai.com',
            categories: ['restaurant', 'sushi'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'sushi' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '5',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 5, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519669, lon: 13.403244 },
          viewport: {
            topLeftPoint: { lat: 52.52057, lon: 13.40177 },
            btmRightPoint: { lat: 52.51877, lon: 13.40472 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51936, lon: 13.40344 } },
          ],
        },
        {
          type: 'POI',
          id: 'm46ixbuE5nnveeuI0RspDg',
          score: 2.5745220184,
          dist: 134.017042,
          info: 'search:ta:276009007440644-DE',
          poi: {
            name: 'Trattoria Peretti',
            phone: '+49 30 27908580',
            categorySet: [{ id: 7315036 }],
            url: 'www.peretti-berlin.com/',
            categories: ['pizza', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'pizza' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '5',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 5, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519962, lon: 13.402975 },
          viewport: {
            topLeftPoint: { lat: 52.52086, lon: 13.4015 },
            btmRightPoint: { lat: 52.51906, lon: 13.40445 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51938, lon: 13.40348 } },
          ],
        },
        {
          type: 'POI',
          id: 'tOh6Jo1BXsv17kYtQeFV7Q',
          score: 2.57452178,
          dist: 135.385861,
          info: 'search:ta:276009023868306-DE',
          poi: {
            name: 'Food Lounge Berlin',
            categorySet: [{ id: 7315018 }],
            url: 'food-lounge-berlin.metro.bar/',
            categories: ['german', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'german' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '4',
            streetName: 'Sankt Wolfgang-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Sankt Wolfgang-Straße 4, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519982, lon: 13.402953 },
          viewport: {
            topLeftPoint: { lat: 52.52088, lon: 13.40148 },
            btmRightPoint: { lat: 52.51908, lon: 13.40443 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51936, lon: 13.40345 } },
          ],
        },
        {
          type: 'POI',
          id: 'I-ezLfrrgGOvCGIwYZzSsw',
          score: 2.57452178,
          dist: 136.460545,
          info: 'search:ta:276007000475458-DE',
          poi: {
            // eslint-disable-next-line quotes
            name: "Andy's Diner & Bar",
            phone: '+49 30 97894120',
            categorySet: [{ id: 7315003 }],
            url: 'www.andysdiner.de/',
            categories: ['american', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'american' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '5',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 5, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519767, lon: 13.402976 },
          viewport: {
            topLeftPoint: { lat: 52.52067, lon: 13.4015 },
            btmRightPoint: { lat: 52.51887, lon: 13.40445 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51963, lon: 13.4039 } },
          ],
        },
        {
          type: 'POI',
          id: 'MacG-99ZKSgIBdpXEt3frA',
          score: 2.5745213032,
          dist: 142.053132,
          info: 'search:ta:276009025529347-DE',
          poi: {
            name: 'Berliner Kartoffelhaus',
            phone: '+49 30 24729373',
            categorySet: [{ id: 7315018 }],
            url: 'www.berliner-kartoffelhaus.de',
            categories: ['german', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'german' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '9',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 9, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.521011, lon: 13.406251 },
          viewport: {
            topLeftPoint: { lat: 52.52191, lon: 13.40477 },
            btmRightPoint: { lat: 52.52011, lon: 13.40773 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52111, lon: 13.40669 } },
          ],
        },
        {
          type: 'POI',
          id: 'EYf1UxFJjb1D7YQ2LKXXMw',
          score: 2.5745213032,
          dist: 141.001682,
          info: 'search:ta:276007000125447-DE',
          poi: {
            name: 'East Craft Beer Restaurant & Bar',
            phone: '+49 30 23458338',
            categorySet: [{ id: 7315021 }],
            url: 'east-craft-bier-restaurant-bar.metro.bar/?lang=en',
            categories: ['hawaiian', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'hawaiian' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '1',
            streetName: 'Heiligegeistkirchplatz',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Heiligegeistkirchplatz 1, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.520439, lon: 13.402995 },
          viewport: {
            topLeftPoint: { lat: 52.52134, lon: 13.40152 },
            btmRightPoint: { lat: 52.51954, lon: 13.40447 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52029, lon: 13.40319 } },
          ],
        },
        {
          type: 'POI',
          id: 'kIdMR_juCtE3i1yUWSrRfw',
          score: 2.5745205879,
          dist: 150.840442,
          info: 'search:ta:276007000379857-DE',
          poi: {
            name: 'Balaustine',
            categorySet: [{ id: 7315106 }],
            categories: ['israeli', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'israeli' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '3',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 3, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.5194, lon: 13.40296 },
          viewport: {
            topLeftPoint: { lat: 52.5203, lon: 13.40148 },
            btmRightPoint: { lat: 52.5185, lon: 13.40444 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51934, lon: 13.40341 } },
          ],
        },
        {
          type: 'POI',
          id: 's1McZowJbtopF_dYeUSzow',
          score: 2.5745205879,
          dist: 151.22272,
          info: 'search:ta:276007000365288-DE',
          poi: {
            name: 'Unfckd Vegan',
            phone: '+49 1512 3326578',
            categorySet: [{ id: 7315015 }],
            url: 'www.unfckd.com',
            categories: ['fast food', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'fast food' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '2',
            streetName: 'Spandauer Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Spandauer Straße 2, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.521172, lon: 13.403802 },
          viewport: {
            topLeftPoint: { lat: 52.52207, lon: 13.40232 },
            btmRightPoint: { lat: 52.52027, lon: 13.40528 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52106, lon: 13.40358 } },
          ],
        },
        {
          type: 'POI',
          id: 'JaFNyB8SQHFbGWbirWKCOQ',
          score: 2.5745203495,
          dist: 152.336228,
          info: 'search:ta:276007000379182-DE',
          poi: {
            name: 'Lindt',
            phone: '+49 30 28046088',
            categorySet: [{ id: 7315 }],
            url: 'www.lindt.de/shops/',
            categories: ['restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ nameLocale: 'en-US', name: 'restaurant' }],
              },
            ],
          },
          address: {
            streetNumber: '5',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 5, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519398, lon: 13.402937 },
          viewport: {
            topLeftPoint: { lat: 52.5203, lon: 13.40146 },
            btmRightPoint: { lat: 52.5185, lon: 13.40441 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51963, lon: 13.4039 } },
          ],
        },
        {
          type: 'POI',
          id: 'ZTurY4hgNcs4Hb553nlWgg',
          score: 2.5745201111,
          dist: 156.433261,
          info: 'search:ta:276009023752426-DE',
          poi: {
            // eslint-disable-next-line quotes
            name: "Schlogl's",
            phone: '+49 30 2411221',
            categorySet: [{ id: 7315018 }],
            url: 'berliner-essen.de',
            categories: ['german', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'german' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '9',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 9, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.521287, lon: 13.405912 },
          viewport: {
            topLeftPoint: { lat: 52.52219, lon: 13.40443 },
            btmRightPoint: { lat: 52.52039, lon: 13.40739 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52111, lon: 13.40669 } },
          ],
        },
        {
          type: 'POI',
          id: '6WmM8j8jj3fOxHis-_JCEw',
          score: 2.5745186806,
          dist: 167.502739,
          info: 'search:ta:276006004327241-DE',
          poi: {
            name: 'Co Kim Kitchen',
            categorySet: [{ id: 7315051 }],
            categories: ['restaurant', 'vietnamese'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'vietnamese' },
                ],
              },
            ],
          },
          address: {
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10435',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: '10435 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52045, lon: 13.40732 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40584 },
            btmRightPoint: { lat: 52.51955, lon: 13.4088 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52009, lon: 13.40778 } },
          ],
        },
        {
          type: 'POI',
          id: 'Qan-I5rNGYHqOtSCzYdEFg',
          score: 2.5745186806,
          dist: 167.502739,
          info: 'search:ta:276007000510429-DE',
          poi: {
            name: 'Freddy Feys Fish & Fries',
            phone: '+49 30 60275029',
            categorySet: [{ id: 7315008 }],
            url: 'www.barkinkitchen.com',
            categories: ['british', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'british' },
                ],
              },
            ],
          },
          address: {
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10999',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: '10999 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52045, lon: 13.40732 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40584 },
            btmRightPoint: { lat: 52.51955, lon: 13.4088 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52009, lon: 13.40778 } },
          ],
        },
        {
          type: 'POI',
          id: 'EtamnPAidLTwointC8fCNg',
          score: 2.5745186806,
          dist: 167.502739,
          info: 'search:ta:276006004329225-DE',
          poi: {
            name: 'Spittlemarkt',
            categorySet: [{ id: 7315 }],
            categories: ['restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ nameLocale: 'en-US', name: 'restaurant' }],
              },
            ],
          },
          address: {
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: '10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52045, lon: 13.40732 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40584 },
            btmRightPoint: { lat: 52.51955, lon: 13.4088 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52009, lon: 13.40778 } },
          ],
        },
        {
          type: 'POI',
          id: 'GQWH5Nyy_7DuytPXvNxCEA',
          score: 2.5745186806,
          dist: 167.502739,
          info: 'search:ta:276006004328672-DE',
          poi: {
            name: 'Tottaria Gino',
            categorySet: [{ id: 7315025 }],
            categories: ['italian', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'italian' },
                ],
              },
            ],
          },
          address: {
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10777',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: '10777 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52045, lon: 13.40732 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40584 },
            btmRightPoint: { lat: 52.51955, lon: 13.4088 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52009, lon: 13.40778 } },
          ],
        },
        {
          type: 'POI',
          id: 'udPcNAyLIXwsF2U5698P5Q',
          score: 2.5745186806,
          dist: 167.502739,
          info: 'search:ta:276007000510415-DE',
          poi: {
            name: 'Pirouette',
            categorySet: [{ id: 7315040 }],
            url: 'www.facebook.com/pirouette.cafebar/',
            categories: ['restaurant', 'russian'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'russian' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'City Centre',
            municipality: 'Berlin',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Germany',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52045, lon: 13.40732 },
          viewport: {
            topLeftPoint: { lat: 52.52135, lon: 13.40584 },
            btmRightPoint: { lat: 52.51955, lon: 13.4088 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52104, lon: 13.40703 } },
          ],
        },
        {
          type: 'POI',
          id: 'o0qwBYmf1kSuOPtgfQ_xXQ',
          score: 2.5745184422,
          dist: 169.541418,
          info: 'search:ta:276007000373608-DE',
          poi: {
            name: 'Haus Ungarn',
            phone: '+49 30 28877450',
            categorySet: [{ id: 7315 }],
            url: 'hausungarn.de/',
            categories: ['restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ nameLocale: 'en-US', name: 'restaurant' }],
              },
            ],
          },
          address: {
            streetNumber: '9',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 9, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.5213, lon: 13.406281 },
          viewport: {
            topLeftPoint: { lat: 52.5222, lon: 13.4048 },
            btmRightPoint: { lat: 52.5204, lon: 13.40776 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52111, lon: 13.40669 } },
          ],
        },
        {
          type: 'POI',
          id: 'fyp5WUTEaVl4o41d4xd9LQ',
          score: 2.5745170116,
          dist: 183.310772,
          info: 'search:ta:276009007582545-DE',
          poi: {
            name: 'Heat',
            categorySet: [{ id: 7315003 }],
            categories: ['american', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'american' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '3',
            streetName: 'Karl-Liebknecht-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Karl-Liebknecht-Straße 3, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.519417, lon: 13.402424 },
          viewport: {
            topLeftPoint: { lat: 52.52032, lon: 13.40095 },
            btmRightPoint: { lat: 52.51852, lon: 13.4039 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.51914, lon: 13.40308 } },
            { type: 'main', position: { lat: 52.51922, lon: 13.40322 } },
          ],
        },
        {
          type: 'POI',
          id: '8-l5WfdWTF8_8AY03yIVSw',
          score: 2.5745158195,
          dist: 191.703386,
          info: 'search:ta:276009023695187-DE',
          poi: {
            name: 'Eden Restaurant',
            phone: '+49 30 76953284',
            categorySet: [{ id: 7315051 }],
            url: 'eden-foodgarden.com',
            categories: ['restaurant', 'vietnamese'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'vietnamese' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '19',
            streetName: 'Rosenstraße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Rosenstraße 19, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.521725, lon: 13.404725 },
          viewport: {
            topLeftPoint: { lat: 52.52262, lon: 13.40325 },
            btmRightPoint: { lat: 52.52083, lon: 13.4062 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52164, lon: 13.4046 } },
          ],
        },
        {
          type: 'POI',
          id: '885s1Let8zihy07q_2t5AQ',
          score: 2.5745129585,
          dist: 215.370271,
          info: 'search:ta:276006000216576-DE',
          poi: {
            name: 'Tipica Gastronomie',
            phone: '+49 30 25099440',
            categorySet: [{ id: 7315033 }],
            url: 'eden-foodgarden.com',
            categories: ['mexican', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'mexican' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '19',
            streetName: 'Rosenstraße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Rosenstraße 19, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.521943, lon: 13.404944 },
          viewport: {
            topLeftPoint: { lat: 52.52284, lon: 13.40347 },
            btmRightPoint: { lat: 52.52104, lon: 13.40642 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52166, lon: 13.40455 } },
          ],
        },
        {
          type: 'POI',
          id: 'd4PIMoc79yQZnEFaz876jQ',
          score: 2.5745122433,
          dist: 219.051027,
          info: 'search:ta:276009023829078-DE',
          poi: {
            name: 'Wrap Me',
            categorySet: [{ id: 7315060 }],
            categories: ['restaurant', 'western continental'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'western continental' },
                  { nameLocale: 'en-US', name: 'restaurant' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '2',
            streetName: 'Sankt Wolfgang-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Sankt Wolfgang-Straße 2, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.51993, lon: 13.401719 },
          viewport: {
            topLeftPoint: { lat: 52.52093, lon: 13.40007 },
            btmRightPoint: { lat: 52.51893, lon: 13.40336 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52092, lon: 13.40147 } },
          ],
        },
        {
          type: 'POI',
          id: 'KQgTbaNSU4j86rz8PgieEw',
          score: 2.5745120049,
          dist: 221.227113,
          info: 'search:ta:276007000378850-DE',
          poi: {
            name: 'Genusskombinat',
            phone: '+49 30 308777515',
            categorySet: [{ id: 7315 }],
            url: 'www.genusskombinat.com',
            categories: ['restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ nameLocale: 'en-US', name: 'restaurant' }],
              },
            ],
          },
          address: {
            streetName: 'Anna-Louisa-Karsch-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Anna-Louisa-Karsch-Straße, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52063, lon: 13.401849 },
          viewport: {
            topLeftPoint: { lat: 52.52153, lon: 13.40037 },
            btmRightPoint: { lat: 52.51973, lon: 13.40333 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52095, lon: 13.40155 } },
          ],
        },
        {
          type: 'POI',
          id: '4E0TJXveujU7KAf8_n7MSg',
          score: 2.574511528,
          dist: 224.068852,
          info: 'search:ta:276006004304534-DE',
          poi: {
            name: 'La Ciccia Berlin',
            phone: '+49 30 30877750',
            categorySet: [{ id: 7315025 }],
            categories: ['italian', 'restaurant'],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { nameLocale: 'en-US', name: 'restaurant' },
                  { nameLocale: 'en-US', name: 'italian' },
                ],
              },
            ],
          },
          address: {
            streetNumber: '2',
            streetName: 'Anna-Louisa-Karsch-Straße',
            municipalitySubdivision: 'Mitte',
            municipality: 'Berlin',
            neighbourhood: 'Spandauer Vorstadt',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionName: 'Berlin',
            countrySubdivisionCode: 'BE',
            postalCode: '10178',
            countryCode: 'DE',
            country: 'Deutschland',
            countryCodeISO3: 'DEU',
            freeformAddress: 'Anna-Louisa-Karsch-Straße 2, 10178 Berlin',
            localName: 'Berlin',
          },
          position: { lat: 52.52019, lon: 13.401656 },
          viewport: {
            topLeftPoint: { lat: 52.52109, lon: 13.40018 },
            btmRightPoint: { lat: 52.51929, lon: 13.40313 },
          },
          entryPoints: [
            { type: 'main', position: { lat: 52.52093, lon: 13.40151 } },
          ],
        },
      ];
      const firstExpectedCluster = [
        {
          address: {
            country: 'Germany',
            countryCode: 'DE',
            countryCodeISO3: 'DEU',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionCode: 'BE',
            countrySubdivisionName: 'Berlin',
            freeformAddress:
              'Karl-Liebknecht-Straße, 10178 Berlin (Spandauer Vorstadt)',
            localName: 'Berlin',
            municipality: 'Berlin',
            municipalitySubdivision: 'City Centre',
            neighbourhood: 'Spandauer Vorstadt',
            postalCode: '10178',
            streetName: 'Karl-Liebknecht-Straße',
          },
          dist: 55.09987,
          entryPoints: [
            { position: { lat: 52.52041, lon: 13.40532 }, type: 'main' },
          ],
          id: '608eM5m11JoTURFCj8jwtQ',
          info: 'search:ta:276009007570466-DE',
          poi: {
            brands: [{ name: 'Block House' }],
            categories: ['restaurant', 'steak house'],
            categorySet: [{ id: 7315045 }],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { name: 'steak house', nameLocale: 'en-US' },
                  { name: 'restaurant', nameLocale: 'en-US' },
                ],
              },
            ],
            name: 'Block House am Alexanderplatz',
            url: 'www.block-house.de/restaurants/berlin/am-alexanderplatz',
          },
          position: { lat: 52.520476, lon: 13.405217 },
          score: 2.5745270252,
          type: 'POI',
          viewport: {
            btmRightPoint: { lat: 52.51958, lon: 13.40669 },
            topLeftPoint: { lat: 52.52138, lon: 13.40374 },
          },
        },
        {
          address: {
            country: 'Deutschland',
            countryCode: 'DE',
            countryCodeISO3: 'DEU',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionCode: 'BE',
            countrySubdivisionName: 'Berlin',
            freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
            localName: 'Berlin',
            municipality: 'Berlin',
            municipalitySubdivision: 'Mitte',
            neighbourhood: 'Spandauer Vorstadt',
            postalCode: '10178',
            streetName: 'Spandauer Straße',
            streetNumber: '4',
          },
          dist: 60.352925,
          distance: 32.71269442946893,
          entryPoints: [
            { position: { lat: 52.52041, lon: 13.40449 }, type: 'main' },
          ],
          id: '5B5J7-cFrvryHFIaMgm0vw',
          info: 'search:ta:276006000353058-DE',
          poi: {
            brands: [{ name: 'Nordsee' }],
            categories: ['restaurant', 'seafood'],
            categorySet: [{ id: 7315043 }],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [
                  { name: 'seafood', nameLocale: 'en-US' },
                  { name: 'restaurant', nameLocale: 'en-US' },
                ],
              },
            ],
            name: 'Nordsee',
            phone: '+49 30 2426881',
            url: 'www.nordsee.com',
          },
          position: { lat: 52.520534, lon: 13.404743 },
          score: 2.5745265484,
          type: 'POI',
          viewport: {
            btmRightPoint: { lat: 52.51963, lon: 13.40622 },
            topLeftPoint: { lat: 52.52143, lon: 13.40327 },
          },
        },
        {
          address: {
            country: 'Deutschland',
            countryCode: 'DE',
            countryCodeISO3: 'DEU',
            countrySecondarySubdivision: 'Berlin',
            countrySubdivision: 'Berlin',
            countrySubdivisionCode: 'BE',
            countrySubdivisionName: 'Berlin',
            freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
            localName: 'Berlin',
            municipality: 'Berlin',
            municipalitySubdivision: 'Mitte',
            neighbourhood: 'Spandauer Vorstadt',
            postalCode: '10178',
            streetName: 'Spandauer Straße',
            streetNumber: '4',
          },
          dist: 65.822336,
          distance: 41.945130745693945,
          entryPoints: [
            { position: { lat: 52.52046, lon: 13.40441 }, type: 'main' },
          ],
          id: 'GAuX8kvkztlyv34oVaWJvg',
          info: 'search:ta:276009023845621-DE',
          poi: {
            categories: ['restaurant'],
            categorySet: [{ id: 7315 }],
            classifications: [
              {
                code: 'RESTAURANT',
                names: [{ name: 'restaurant', nameLocale: 'en-US' }],
              },
            ],
            name: 'Palm Beach',
            phone: '+49 30 97004660',
            url: 'www.palm-beach-berlin.de/',
          },
          position: { lat: 52.520561, lon: 13.404613 },
          score: 2.57452631,
          type: 'POI',
          viewport: {
            btmRightPoint: { lat: 52.51966, lon: 13.40609 },
            topLeftPoint: { lat: 52.52146, lon: 13.40314 },
          },
        },
      ];

      const groupedLocations = clusterLocationsTogether(
        tomTomAPILocations,
        null
      );

      expect(true).toBeTruthy();

      expect(groupedLocations.length < tomTomAPILocations.length).toBeTruthy();
      expect(groupedLocations[0]).toEqual(firstExpectedCluster);
    });
  });

  describe('mapClusterIntoAddress', () => {
    it('should summarize the cluster', () => {
      const anchorLocation = {
        address: {
          country: 'Germany',
          countryCode: 'DE',
          countryCodeISO3: 'DEU',
          countrySecondarySubdivision: 'Berlin',
          countrySubdivision: 'Berlin',
          countrySubdivisionCode: 'BE',
          countrySubdivisionName: 'Berlin',
          freeformAddress:
            'Karl-Liebknecht-Straße, 10178 Berlin (Spandauer Vorstadt)',
          localName: 'Berlin',
          municipality: 'Berlin',
          municipalitySubdivision: 'City Centre',
          neighbourhood: 'Spandauer Vorstadt',
          postalCode: '10178',
          streetName: 'Karl-Liebknecht-Straße',
        },
        dist: 55.09987,
        entryPoints: [
          { position: { lat: 52.52041, lon: 13.40532 }, type: 'main' },
        ],
        id: '608eM5m11JoTURFCj8jwtQ',
        info: 'search:ta:276009007570466-DE',
        poi: {
          brands: [{ name: 'Block House' }],
          categories: ['restaurant', 'steak house'],
          categorySet: [{ id: 7315045 }],
          classifications: [
            {
              code: 'RESTAURANT',
              names: [
                { name: 'steak house', nameLocale: 'en-US' },
                { name: 'restaurant', nameLocale: 'en-US' },
              ],
            },
          ],
          name: 'Block House am Alexanderplatz',
          url: 'www.block-house.de/restaurants/berlin/am-alexanderplatz',
        },
        position: { lat: 52.520476, lon: 13.405217 },
        score: 2.5745270252,
        type: 'POI',
        viewport: {
          btmRightPoint: { lat: 52.51958, lon: 13.40669 },
          topLeftPoint: { lat: 52.52138, lon: 13.40374 },
        },
      };
      const cluster = [
        [
          {
            ...anchorLocation,
          },
          {
            address: {
              country: 'Deutschland',
              countryCode: 'DE',
              countryCodeISO3: 'DEU',
              countrySecondarySubdivision: 'Berlin',
              countrySubdivision: 'Berlin',
              countrySubdivisionCode: 'BE',
              countrySubdivisionName: 'Berlin',
              freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
              localName: 'Berlin',
              municipality: 'Berlin',
              municipalitySubdivision: 'Mitte',
              neighbourhood: 'Spandauer Vorstadt',
              postalCode: '10178',
              streetName: 'Spandauer Straße',
              streetNumber: '4',
            },
            dist: 60.352925,
            distance: 32.71269442946893,
            entryPoints: [
              { position: { lat: 52.52041, lon: 13.40449 }, type: 'main' },
            ],
            id: '5B5J7-cFrvryHFIaMgm0vw',
            info: 'search:ta:276006000353058-DE',
            poi: {
              brands: [{ name: 'Nordsee' }],
              categories: ['restaurant', 'seafood'],
              categorySet: [{ id: 7315043 }],
              classifications: [
                {
                  code: 'RESTAURANT',
                  names: [
                    { name: 'seafood', nameLocale: 'en-US' },
                    { name: 'restaurant', nameLocale: 'en-US' },
                  ],
                },
              ],
              name: 'Nordsee',
              phone: '+49 30 2426881',
              url: 'www.nordsee.com',
            },
            position: { lat: 52.520534, lon: 13.404743 },
            score: 2.5745265484,
            type: 'POI',
            viewport: {
              btmRightPoint: { lat: 52.51963, lon: 13.40622 },
              topLeftPoint: { lat: 52.52143, lon: 13.40327 },
            },
          },
          {
            address: {
              country: 'Deutschland',
              countryCode: 'DE',
              countryCodeISO3: 'DEU',
              countrySecondarySubdivision: 'Berlin',
              countrySubdivision: 'Berlin',
              countrySubdivisionCode: 'BE',
              countrySubdivisionName: 'Berlin',
              freeformAddress: 'Spandauer Straße 4, 10178 Berlin',
              localName: 'Berlin',
              municipality: 'Berlin',
              municipalitySubdivision: 'Mitte',
              neighbourhood: 'Spandauer Vorstadt',
              postalCode: '10178',
              streetName: 'Spandauer Straße',
              streetNumber: '4',
            },
            dist: 65.822336,
            distance: 41.945130745693945,
            entryPoints: [
              { position: { lat: 52.52046, lon: 13.40441 }, type: 'main' },
            ],
            id: 'GAuX8kvkztlyv34oVaWJvg',
            info: 'search:ta:276009023845621-DE',
            poi: {
              categories: ['restaurant'],
              categorySet: [{ id: 7315 }],
              classifications: [
                {
                  code: 'RESTAURANT',
                  names: [{ name: 'restaurant', nameLocale: 'en-US' }],
                },
              ],
              name: 'Palm Beach',
              phone: '+49 30 97004660',
              url: 'www.palm-beach-berlin.de/',
            },
            position: { lat: 52.520561, lon: 13.404613 },
            score: 2.57452631,
            type: 'POI',
            viewport: {
              btmRightPoint: { lat: 52.51966, lon: 13.40609 },
              topLeftPoint: { lat: 52.52146, lon: 13.40314 },
            },
          },
        ],
      ];

      const expectedSummary = {
        ...anchorLocation,
        poi: {
          ...anchorLocation.poi,
          name: 'Block House am Alexanderplatz, Nordsee, Palm Beach close to,,',
        },
      };

      const summarizedLocations = getClusterSummarizer('UK')(cluster);
      expect(summarizedLocations.length).toEqual(1);
      expect(typeof summarizedLocations[0]).toEqual('object');
      expect(summarizedLocations[0]).toEqual(expectedSummary);
    });
  });
});
