import { isMunicipality } from './suitable-geocode-options.service';

const exampleLocations = [
  {
    type: 'Geography',
    id: 'xyZXuwaKAj6yE3Ed4Sjgaw',
    score: 2.5488266945,
    dist: 14366.17031048349,
    entityType: 'Municipality',
    matchConfidence: { score: 0.884509204568762 },
    address: {
      municipality: 'Lübben (Spreewald)',
      countrySecondarySubdivision: 'Dahme-Spreewald',
      countrySubdivision: 'Brandenburg',
      countrySubdivisionName: 'Brandenburg',
      countrySubdivisionCode: 'BB',
      countryCode: 'DEU',
      country: 'Deutschland',
      countryCodeISO3: 'DEU',
      freeformAddress: 'Lübben (Spreewald)',
    },
    position: { lat: 51.94154, lon: 13.898 },
    viewport: { topLeftPoint: [Object], btmRightPoint: [Object] },
    boundingBox: { topLeftPoint: [Object], btmRightPoint: [Object] },
    dataSources: { geometry: [Object] },
  },
  {
    type: 'Street',
    id: 'q2hDyxecVcthsRrIKC0QtA',
    score: 2.096146822,
    dist: 382035.86560512654,
    matchConfidence: { score: 1 },
    address: {
      streetName: 'Lübbenstraße',
      municipalitySubdivision: 'Gröpelingen',
      municipality: 'Bremen',
      countrySecondarySubdivision: 'Bremen',
      countrySubdivision: 'Bremen',
      countrySubdivisionName: 'Bremen',
      countrySubdivisionCode: 'HB',
      postalCode: '28237',
      countryCode: 'DEU',
      country: 'Deutschland',
      countryCodeISO3: 'DEU',
      freeformAddress: 'Lübbenstraße, 28237 Bremen',
      localName: 'Bremen',
    },
    position: { lat: 53.11053, lon: 8.77286 },
    viewport: { topLeftPoint: [Object], btmRightPoint: [Object] },
  },
  {
    type: 'Street',
    id: 'pevYBCQiPv-uktJn25ajjw',
    score: 2.0960867405,
    dist: 416341.90914991306,
    matchConfidence: { score: 1 },
    address: {
      streetName: 'Lübbenstraße',
      municipalitySubdivision: 'Atens',
      municipality: 'Nordenham',
      countrySecondarySubdivision: 'Wesermarsch',
      countrySubdivision: 'Niedersachsen',
      countrySubdivisionName: 'Niedersachsen',
      countrySubdivisionCode: 'NI',
      postalCode: '26954',
      countryCode: 'DEU',
      country: 'Deutschland',
      countryCodeISO3: 'DEU',
      freeformAddress: 'Lübbenstraße, 26954 Nordenham',
      localName: 'Nordenham',
    },
    position: { lat: 53.49014, lon: 8.4722 },
    viewport: { topLeftPoint: [Object], btmRightPoint: [Object] },
  },
  {
    type: 'Street',
    id: 'dPWJB1oCo1mW0UVGABwnEQ',
    score: 2.096051693,
    dist: 449919.9084402098,
    matchConfidence: { score: 1 },
    address: {
      streetName: 'Lübbenstraße',
      municipalitySubdivision: 'Hooksiel',
      municipality: 'Wangerland',
      countrySecondarySubdivision: 'Friesland',
      countrySubdivision: 'Niedersachsen',
      countrySubdivisionName: 'Niedersachsen',
      countrySubdivisionCode: 'NI',
      postalCode: '26434',
      countryCode: 'DEU',
      country: 'Deutschland',
      countryCodeISO3: 'DEU',
      freeformAddress: 'Lübbenstraße, 26434 Wangerland',
      localName: 'Wangerland',
    },
    position: { lat: 53.63346, lon: 8.02313 },
    viewport: { topLeftPoint: [Object], btmRightPoint: [Object] },
  },
  {
    type: 'Street',
    id: '-K6ZixjkJTD9wHUewUl7OA',
    score: 2.0755474567,
    dist: 408744.8249046058,
    matchConfidence: { score: 0.9183210977830623 },
    address: {
      streetName: 'Karl-Lübben-Straße',
      municipalitySubdivision: 'Schiffdorferdamm',
      municipality: 'Bremerhaven',
      countrySecondarySubdivision: 'Bremerhaven',
      countrySubdivision: 'Bremen',
      countrySubdivisionName: 'Bremen',
      countrySubdivisionCode: 'HB',
      postalCode: '27574',
      countryCode: 'DEU',
      country: 'Deutschland',
      countryCodeISO3: 'DEU',
      freeformAddress: 'Karl-Lübben-Straße, 27574 Bremerhaven',
      localName: 'Bremerhaven',
    },
    position: { lat: 53.53436, lon: 8.63294 },
    viewport: { topLeftPoint: [Object], btmRightPoint: [Object] },
  },
];

describe('SuitableGeocodeOptionsService', () => {
  describe('isMunicipality', () => {
    it('should return true', () => {
      expect(isMunicipality(exampleLocations[0])).toBe(true);
    });
  });
});
