const OPERATOR_NAMES = [
  '800 Volt',
  'A2A E-mobility S.r.l.',
  'Abel',
  'ABF',
  'Acea Innovation S.r.l.',
  'à CEPSA CPO',
  'ADVANCE SOLUCIONES DE NEGOCIO S.L.',
  'AgeVolt',
  'AggerEnergie GmbH',
  'Ägidius Keferloh GmbH',
  'Agilent Technologies Deutschland GmbH',
  'AGSM AIM CPO',
  'Allego',
  'Plugsurfing',
  'Allgäuer Integrationsbetrieb',
  'Allgäuer Kraftwerke',
  'Allgäuer Überlandwerk',
  'Alpiq E-Mobility AG',
  'AMPECO Ltd.',
  'BP Pulse',
  'Enel X',
  'ARAL',
  'GreenWay',
  'Qwello',
  'EVBox',
  'Vattenfall InCharge',
  'ampido GmbH',
  'André Laukner / Solarmotion GmbH',
  'APCOA PARKING Austria',
  'AP&S International GmbH',
  'Atlante',
  'AUDI AG',
  'Autel Intelligent Technology',
  'Autocenter Altmittweida GmbH',
  'Auto Griese',
  'Autohaus Brosch GmbH',
  'Autohaus Drexler',
  'Autohaus Kapinsky',
  'Autohaus Keller',
  'Autohaus Schaden',
  'autoSense AG',
  'Auto Singer GmbH & Co. KG',
  'Auto SPREVES GmbH',
  'Autostrom Einert GmbH & Co. KG.',
  'AÜW powered by Soloplan',
  'avency GmbH',
  'AVIA Volt',
  'Axpo Energy Solutions Italia S.p.A.',
  'Barnimer Energiebeteiligungsgesellschaft mbH',
  'Be Charge s.r.l.',
  'Berger Stromversorgungen GmbH & Co. KG',
  'Berliner Stadtwerke',
  'Bernd Veeser Solar und Energie',
  'Berner Elektrotechnik GmbH',
  'BE Solution GmbH',
  'Best Western Hotel Am Papenberg',
  'BE Vertrieb GmbH & Co KG',
  'Bidirex GmbH',
  'BIGGE ENERGIE GmbH & Co. KG',
  'BK Benzin-Kontor AG',
  'Blaser Group GmbH',
  'Blue Corner',
  'Bocholter Energie- und Wasserversorgung GmbH',
  'bode & Stephan GmbH',
  'Böhm Emobility Inh. Martin Böhm',
  'Bosch Charging Solutions GmbH',
  'Braviscasa GmbH',
  'BS|ENERGY',
  'Burgenland Energie',
  'ByWatt',
  'CARF - Bornes Publiques',
  'Carl Knauber Holding GmbH & Co. KG',
  'Carsten Schwarz',
  'Censo',
  'CEZ, a. s.',
  'charge.brussels',
  'Chargecloud',
  'ChargeGuru',
  'ChargeIQ GmbH',
  'chargeIT mobility',
  'Chargemaker GmbH',
  'ChargeNet NZ',
  'ChargeOne',
  'ChargePanel',
  'Chargepartner Network GmbH',
  // 'ChargePoint Austria GmbH', // TODO removing this operator for now because of the conflict with charge Point
  'ChargeUp Services CZ s.r.o.',
  'Chargy',
  'NewMotion',
  'Chemnitzer Siedlungsgemeinschaft eG',
  'Cine-Verwaltungs-GmbH',
  'CityCharging B.V.',
  'CKW',
  'Clever',
  'Clever A/S',
  'Columbus Energy S.A.',
  'Comfortcharge GmbH',
  'Commercial Charger GmbH',
  'Compleo Charging Software GmbH',
  'ConnectNed',
  'Cooperatie AVIA Nederland U.A.',
  'CPO Joulz Belgium',
  'Cross Market Places GmbH',
  'CUBOS GmbH',
  'Currenta GmbH & Co. OHG',
  'DAH Engineering GmbH',
  'DA Holding GmbH',
  'Danzer Gastronomie GmbH',
  'DB Energie',
  'Deer GmbH',
  'Dekra Deutschland',
  'Der Elektroprofi GmbH',
  'DEW21 GmbH',
  'DHS Grundstücksverwaltung UG Co. KG',
  'DKV Mobility-Germany',
  'Dorfentwicklungs-GmbH Wildpoldsried',
  'Dortmunder Energie- und Wasserversorgung GmbH',
  'drivee ApS',
  'Dr.Martin Quarz',
  'Duferco Energia SpA',
  'EAAZE GmbH',
  'EB Charging',
  'Ebee Smart Technologies GmbH',
  'eCarUp AG',
  'EClearing',
  'e-clearing.net',
  'Eco.Tech neue Energien & Technik GmbH',
  'EDELRID GmbH & Co.KG',
  'EDP Clientes, S.A.',
  'Eduard Walk KG',
  'eeproperty',
  'eins energie in sachsen GmbH & Co. KG',
  'EKOEN Sp. z o.o.',
  'Enercity',
  'e-laden Tirol GmbH',
  'ELECTRA SAS',
  'ElectricBlue',
  'ELECTRIQUA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ',
  'Electris',
  'Elektrizitäts-Genossenschaft Rettenberg',
  'Elektrizitätswerk Hindelang',
  'Elektro Ehinger GmbH',
  'Elektro Keßler GmbH',
  'Elektro Kock GmbH & Co.KG',
  'Elektrotechnik Mühmel',
  'Eleport Innovations OÜ',
  'ELMŰ-ÉMÁSZ Solutions Kft.',
  'Elocity Sp z o. o.',
  'EMobility Netzwerk Deutschland GmbH',
  'Energie Südbayern GmbH',
  'Energie und Wasser Potsdam GmbH',
  'Energieversorgung Filstal GmbH & Co. KG',
  'EnBW',
  'Endesa',
  'ENGIE MAMP - Bornes publiques',
  'EQUANS',
  'Eulektro GmbH',
  'EVnetNL',
  'EV Wise',
  'EVzen',
  'EWE',
  'EWE go be.storaged GmbH',
  'EZdrive',
  'Fastned',
  'Floading',
  'Gemeindewerke Krauchenwies',
  'GFX-NL PitPoint',
  'GGEW',
  'GMOB',
  'GoFast',
  'Greenflux',
  'Interparking Belgium',
  'IONITY',
  'Joulz',
  'Ladebusiness',
  'Ladenetz',
  'Last Mile Solutions',
  'Magenta',
  'MBLTY',
  'MegaCharge',
  'Mer Germany GmbH',
  'NlCharge',
  'Norauto - Bornes publiques',
  'Numbat GmbH',
  'Paul Rigby Ltd',
  'PitPoint',
  'PowerDot',
  'Powerstop',
  'RhönEnergie Fulda GmbH',
  'SOMIMAR - Bornes publiques',
  'Sparki',
  'Pfalzwerke',
  'Spiegler Photovoltaikanlagen',
  'Stadtwerke Aachen AG',
  'Stadtwerke Ingolstadt',
  'Stadtwerke Dinslaken GmbH',
  'Stadtwerke Düsseldorf AG',
  'Stadtwerke Neu-Isenburg GmbH',
  'Stadtwerke Neuss Energie und Wasser GmbH',
  'Stadtwerke Radolfzell GmbH',
  'Stadtwerke Stendal GmbH',
  'Stadtwerke Vilsbiburg',
  'Stadtwerke München',
  'Stromnetz Hamburg',
  'SWE Energie GmbH',
  'Shell Recharge',
  'Tesla',
  'Tesla Supercharger',
  'Telekom',
  'Thüringer Energie AG',
  'TotalEnergies',
  'UKPN',
  'ÜZ Mainfranken eG',
  'WIM Energy',
  'Yeet Belgium',
  'AVIA',
  'bp pulse',
  'Bluecharge',
  'Cable Exanergia Portugal',
  'CAR2PLUG',
  'Cascais Proxima',
  'Cepsa',
  'CH*EBM',
  'CH*SWI',
  'Circuitos',
  'Communauté de Communes de la Côtière à Montluel',
  'Communauté de Communes de la Haute Vallée de Chevreuse (CCHVC)',
  'Communauté de Communes Vitry, Champagne et Der',
  'Cooperativa Elétrica de Vale d´Este',
  'Docuworld',
  'E-Zdrive',
  'Eco-Pi',
  'EG Retail SAS',
  'EMACOM',
  'EMEL',
  'Enercom',
  'EV Power',
  'EVCE Power',
  'Ecoinside',
  'FI*001',
  'FR*0NX',
  'FR*A02',
  'FR*A04',
  'FR*ADP',
  'FR*ATL',
  'FR*BDO',
  'FR*CAR',
  'FR*C2A',
  'FR*DS6',
  'FR*E08',
  'FR*ECP',
  'FR*ETI',
  'FR*GRN',
  'FR*H16',
  'FR*IKA',
  'FR*IIM',
  'FR*LPI',
  'FR*LOD',
  'FR*LST',
  'FR*MEL',
  'FR*MFC',
  'FR*N54',
  'FR*PAM',
  'FR*PHI',
  'FR*PY1',
  'FR*QPK',
  'FR*QWT',
  'FR*SMI',
  'FR*S54',
  'FR*S59',
  'FR*S62',
  'FR*S88',
  'FR*WA1',
  'FR*WA2',
  'FR*WA3',
  'FR*WA4',
  'FR*WA6',
  'FR*WA7',
  'FR*WA8',
  'FR*WA9',
  'FR*Y55',
  'FR*Z24',
  'FR*Z33',
  'FR*Z44',
  'FR*Z55',
  'FR*Z64',
  'FR*Z74',
  'FR*Z87',
  'FR*Z99',
  'GiC - Gestion Inteligente de Cargas',
  'Goldenergy',
  'Hexagonal Ocean',
  'iHome',
  'IBIL Gestor de Carga de VE S.A.',
  'IONITY',
  'IT*220',
  'IT*AEV',
  'IT*AMO',
  'IT*DUF',
  'IT*ELC',
  'IT*GFX',
  'IT*IOY',
  'IT*KOS',
  'IT*TFC',
  'iZivia',
  "LUMI'iN",
  'Loulé Concelho Global',
  'Mota-Engil Renewing',
  'MEGA ENERGIES',
  'Mobilygreen',
  'Move in Pure',
  'Município de Santa Cruz',
  'NO*ION',
  'NL*ABL',
  'NL*BWT',
  'NL*CPI',
  'NL*JEG',
  'NL*LKS',
  'PACORP, LDA',
  'Petrotermica Energia, S.A.',
  'PROVIRIDIS',
  'RD Brest',
  'Régie Services Energie',
  'Réseau Sarthe IRVE',
  'Rungis Marché International',
  'Saemes',
  'Shell Recharge',
  'SIEGE27',
  'SIED70',
  'SDE22',
  'SDE35',
  'SDE76',
  'SDE82',
  'SDEER 17',
  'SDEG',
  'SDED52',
  'SDEPA',
  'SDEEG',
  'SDEPA',
  'SORÉGIES',
  'SunEnergy',
  'SYDEC',
  'SYDED',
  'Syndicat de la Diège',
  "Syndicat de l'Énergie de l'Orne",
  "Syndicat Départemental d'Electricité et de Gaz de Charentes",
  "Territoire d'Energie 90",
  "Territoire d'énergie Puy-de-Dôme",
  'Ucharge',
  'Veimonte',
  'Ville de la Garenne Colombes',
  "Ville d'Avray",
  'Ville de Rosheim',
  'Wenea',
  'Zephyre',
  'Zyklus',
];

const MUV_OPERATOR_NAMES = [
  'AVIA',
  'Aix-Marseille Provence Métropole',
  'Alfa Energia',
  'Alizé',
  'Allego',
  'Alterbase Seolis',
  'Atlante',
  'Autorecharge',
  'BE CABLE',
  'BELIB',
  'BORNES SOLUTIONS',
  'Be Charge',
  'Bluecharge',
  'Bluint',
  'Bornes Solutions',
  'Bump charge',
  'CAR2PLUG',
  'CITEOS',
  'CME',
  'Cable Exanergia Portugal',
  'Camping du Lac',
  'Capwatt',
  'Cargga Inteligente',
  'Carrefour Property',
  'Cascais Proxima',
  'Cepsa',
  // 'ChargePoint', // TODO removing this operator for now because of the conflict with charge Point
  'ChargePoly',
  'Circuitos',
  'Communauté Urbaine Grand Paris Seine & Oise',
  "Communauté d'Agglomération Paris",
  "Communauté d'agglomération Paris-Saclay",
  'Communauté de Communes Vitry, Champagne et Der',
  'Communauté de Communes de la Côtière à Montluel',
  'Communauté de Communes de la Haute Vallée de Chevreuse (CCHVC)',
  "Communauté de Communes de la Plaine de l'Ain",
  'Communauté de communes Vallée des Baux-Alpilles',
  "Cooperativa Elétrica de Vale d'Este",
  'DRIVECO',
  'Distrifrio Supermercados',
  'Docuworld',
  'Douromobe',
  'E-Mobility SAP Labs Mougins',
  'E-Plug',
  'E-Totem',
  'E. Leclerc',
  'E.Zdrive',
  'EDP',
  'EFFIA Stationnement',
  'EG Retail SAS',
  'EMACOM',
  'EMEL',
  'EPOCH',
  'EV Power',
  'EVBox B.V.',
  'EVCE Power',
  'EVIO',
  'EasyCharge',
  'Eco-Pi',
  'Ecoinside',
  'Electra',
  'Electric 55 Charging',
  'Electromaps',
  'Elergone Energia',
  'Eletec',
  'Emobtec',
  'Eneco eMobility GmbH',
  'Enercom',
  "Etablissement Public d'Aménagement de Paris-Saclay",
  'Evaz',
  'Exadys',
  'Ez-Charg3',
  'Ezu Energia',
  'FRONTROW',
  'Factor Energia',
  'GASFOMENTO - Sistemas e Instalações de Gás, S.A.',
  'GEMO Trignac',
  'Galp Geste',
  'Galp Power',
  'Generation Journey',
  'GiC - Gestion Inteligente de Cargas',
  'Goldenergy',
  'Golf Club de Lyon',
  'Green Evolut',
  'GreenCharge',
  'Greenflux',
  'Greenspot',
  'Grenoble-Alpes Métropole',
  'Grupo Easycharger, SL',
  'Helexia',
  'Hexagonal Ocean',
  'High Green Power',
  'IBIL',
  'INDIGO',
  'INOUid',
  'INTERTROFA',
  'IZIVIA',
  'Iberdrola',
  'Image4all',
  'Instavolt Portugal Lda.',
  'Interparking',
  'Intervilapraia',
  'Ionity',
  'Izivia Wiiiz',
  'JJTomé',
  'Low Cost',
  "LUMI'iN",
  'Last Mile Solutions',
  'Le Mans Métropole',
  'Loulé Concelho Global',
  'Luzigás',
  'MEA ENERGIES',
  'MEO',
  'MODULO',
  'MOON',
  'MUVEXT',
  'Maksu Services',
  'Metropole du Grand Nancy',
  'Metropolis Grand Paris',
  'Mobel',
  'Mobi.e',
  'Mobiletric',
  'Mobilygreen',
  'Morbihan Energies',
  'Mota-Engil Renewing',
  "Mouv'Oise",
  'Move in Pure',
  'Município de Santa Cruz',
  'Métropole Rouen-Normandie',
  'NW IECharge',
  'Neureifen',
  "Offer of Territoire d'Energie Mayenne",
  'Optimile Network',
  'PACORP',
  'PETROTERMICA ENERGIA',
  'PROVIRIDIS',
  'Parking de Toulouse',
  'Pays de la Loire',
  'Petroassist',
  'Power Dot',
  'Prio.E',
  'Prise de Nice',
  'Propel-Cepsa',
  'Qovoltis',
  'RD Brest',
  'Rambouillet Territoires',
  'Repsol',
  'RossiniEnergy',
  'Rungis Marché International',
  'Régie Services Energie',
  'Réseau Sarthe IRVE',
  'Révéo',
  'SDEC Energie',
  'SEY ma borne - Yvelines',
  'SGA MOBILITY',
  'SHELL',
  'SYDELA 44',
  'SYDER',
  'Saemes',
  'Saint Etienne Métropole',
  'Segma',
  'Sevdec',
  'Shell Recharge',
  'Silver Ridge - Asset Management',
  'Siège Les Mousquetaires',
  'Sodibraga - Supermercados Lda',
  'Sorégies',
  'Stadtwerke Schwedt',
  'Stations-e',
  'SunEnergy',
  'SuperFafe',
  'SuperGuimaraes',
  'Superareosa Supermercados',
  'Supermarchés COLRUYT',
  'SyDEV',
  "Syndicat Départemental d'Electricité et de Gaz de Charentes",
  "Syndicat Départemental d'Énergie De la Haute-Garonne (SDEHG)",
  "Syndicat Départemental d'Énergies de l'Yonne (SDEY89)",
  'Syndicat Départemental des Energies de la Creuse',
  'Syndicat Départemental Énergie Aube (SDEA)',
  "Syndicat d'Energie Vauclusien",
  "Syndicat de l'Énergie de l'Orne",
  'Syndicat de la Diège',
  'Syndicat mixte des Transports du bassin de Briey',
  'TOULIBEO',
  "Territoire d'Energie 90",
  "Territoire d'Energie d'Alsace",
  "Territoire d'énergie Puy-de-Dôme",
  'TotalEnergies',
  'UNIBAIL',
  'USEDA',
  'Ucharge',
  'VISACASA',
  'Veimonte',
  "Ville d'Avray",
  'Ville de Beynes',
  'Ville de Blagnac',
  'Ville de Revel',
  'Ville de Rosheim',
  'Ville de Sablé-sur-Sarthe',
  'Ville de Viriat',
  'Ville de la Garenne Colombes',
  'Virta',
  'WAAT',
  'Wenea',
  'WowPlug',
  'ZE-WATT',
  'ZEborne',
  'Zephyre',
  'Zunder',
  'bp pulse',
  'chargecloud Network',
  'e-Totem',
  'e-nergyze',
  'eborn',
  'has.to.be',
  'iHome',
  'izivia',
  'la borne bleue',
  'neutral-payment-provider',
  'mobilygreen',
  'pass pass électrique',
];

const NeutralPartner_OPERATOR_NAMES = [
  '50five',
  '800 Volt Technologies',
  'AAE Naturstrom',
  'ALDI Süd',
  'ALVERI',
  'AMPLICITY',
  'AMT_VIOEL_FOLLOWER',
  'APCOA',
  'ATK9P',
  'AUDI',
  'AVIA',
  'AVP E-Mobility',
  'Abel&co',
  'Accor',
  'AgeVolt',
  'AggerEnergie',
  'Agrisnellaad',
  'Aimo Charge',
  'Alfen',
  'Alizé',
  'Allego',
  'AllgäuStrom Mobil',
  'Allgäuer Kraftwerke',
  'Allgäuer Überlandwerk',
  'Aral Pulse',
  'Arinea',
  'Atlante',
  'Auchan',
  'Audi charging hub',
  'Auer Bau',
  'Autohaus Laboe',
  'Autostrom Einert',
  'Avacon',
  'Awesems',
  'BBPARKHAUS',
  'BE Solution',
  'BELKAW',
  'BEOPT',
  'BESPK',
  'BETAP',
  'BEWTF',
  'BEZMS',
  'BIGGE Energie',
  'BMW Charging @Destination',
  'BMW Destination',
  'BMW GroupCharging',
  'BP Pulse',
  'BS|ENERGY',
  'BayWa',
  'Bayernwerk',
  'Be Charge',
  'Beagleplug',
  'Berliner Stadtwerke',
  'Best in Parking',
  'Bidirex',
  'Billa',
  'Blink Charging',
  'Blue Corner',
  'Blue Current',
  'BlueMarble Charging',
  'Blulinc',
  'Bocholter Energie- und Wasserversorgung',
  'Borneco',
  'Bornes Solutions',
  'Bornevo Connect',
  'Bosch',
  'Bravida',
  'Bravida Charge',
  'Budimex Mobility',
  'Bump',
  'Buscher Service',
  'ByWatt',
  'CHGFT',
  'CITYWATT',
  'CKW',
  'COCHARGE',
  'Calix',
  'Car2Plug',
  'CenEnergy',
  'Censo',
  'Charge Construct',
  'ChargeGuru',
  'ChargeLab',
  'ChargeNode',
  'ChargeOne',
  'ChargePoint',
  'ChargeUp',
  'ChargeUp Services CZ',
  'Chargee',
  'Chargee eMobility',
  'Chargemaker',
  'Chargewell Netherlands',
  'Chargy',
  'Circle K',
  'CityCharging',
  "Clem'",
  'Clever',
  'Colruyt',
  'Columbus Energy',
  'Comfortcharge',
  'Compleo',
  'Compleo Connect',
  'Connect Infra',
  'ConnectNed',
  'CutPower',
  'DATS 24',
  'DE110',
  'DEBCK',
  'DEBRI',
  'DECM2',
  'DEEDL',
  'DEEJI',
  'DEEMC',
  'DEINF',
  'DELA1',
  'DENUM',
  'DESPI',
  'DESUE',
  'DEWIS',
  'DRIVECO',
  'Decat',
  'Denkfabrik im Grünen',
  'Deurloo Elektro',
  'Diego Luxembourg',
  'Dortmunder Energie- und Wasserversorgung',
  'Dutch Charge',
  'Décathlon',
  'E-Flux',
  'E-MAXX',
  'E-Sprit',
  'E-Werk Mittelbaden',
  'E.Leclerc',
  'E.ON',
  'EA Energiearchitektur',
  'EAutozas',
  'ECOTAP',
  'EFFIA',
  'EM',
  'EM1',
  'ENERGIEVERSORGUNGDAHLENBURGBLECKEDE',
  'ENERSTOCK',
  'ENGIE',
  'ENIO',
  'ENNAGY',
  'EQUANS',
  'EQUAY',
  'ERFURT E-Mobility',
  'ESERA',
  'ETECNIC',
  'EV Company',
  'EV Map',
  'EV-Point',
  'EVBox',
  'EVD Energieversorgung Dormagen',
  'EVECHARGE',
  'EVL',
  'EVMAPA',
  'EVN',
  'EVnetNL',
  'EVplus',
  'EVzen',
  'EWAGKAMENZ',
  'EWE',
  'EWR',
  'EZ Charge',
  'Edeka',
  'Ekoen',
  'Elbud',
  'Electra',
  'ElectraClear',
  'Electric 55',
  'Electric by D’ieteren',
  'Electriease',
  'ElectroDrive',
  'Electromaps',
  'Elektro Profi',
  'Eleport',
  'Eliso',
  'Elli - VW Group',
  'Elocity',
  'Emobility - East Thomas Walther',
  'Emobility Netzwerk',
  'Emscher Lippe Energie',
  'EnBW',
  'Eneco',
  'Enefit VOLT',
  'Enel X Way',
  'Enercharge',
  'Enercity',
  'Energa',
  'Energa Oświetlenie',
  'Energie 360°',
  'Energie Burgenland',
  'Energie Calw',
  'Energie Graz',
  'Energie Klagenfurt',
  'Energie Mark Brandenburg',
  'Energie OÖ',
  'Energie Steiermark',
  'Energie Südbayern',
  'Energiedienst',
  'Energiedienst AG - Schweiz',
  'Energieversorgung Gera',
  'Energieversorgung Hildesheim',
  'Energieversorgung Kleinwalsertal',
  'Energieversorgung Limburg',
  'EnergyVision',
  'Envia',
  'Eponet',
  'Equans Amsterdam P1',
  'Equans Groningen Drenthe',
  'Eulektro',
  'Evadea',
  'Eviny',
  'Eway',
  'Eways',
  'Expert Kessler',
  'Extendas',
  'F1RST',
  'FIRMENLADEN',
  'FR3R3',
  'FRAPORT_AG_PARKEN',
  'FRDRE',
  'FREVM',
  'FREVZ',
  'FRFLB',
  'FRIEN',
  'FRIIM',
  'FRIKA',
  'FRMFC',
  'FRS54',
  'FRY55',
  'Fastned',
  'Ferratec Technics',
  'Floading',
  'Fluctis',
  'Fraport',
  'Fraunhofer IMM',
  'Freshmile',
  'G&V',
  'GFC – Gesellschaft des Kreises Coesfeld zur Förderung regenerativer Energien',
  'GLS',
  'GO+ EAuto',
  'GOFAST',
  'GP Joule Connect',
  'GROEMITZ',
  'GTIS charging SK',
  'Gelsenwasser',
  'Go Electric Stations',
  'Go-Blue',
  'Goodmoovs',
  'Green Motion',
  'GreenFlux',
  'GreenVesting',
  'GreenWay',
  'Greencharge',
  'Greenman Energy Operations',
  'Greenspot',
  'Greenyellow',
  'Grid & Co.',
  'HEOS',
  'HOCHTIEF Ladepartner',
  'HUMMEL Systemhaus',
  'HUTEA',
  'Hamburger Energiewerke Mobil',
  'Harz Energie',
  'Hertener Stadtwerke',
  'Hey! Charging',
  'HomE',
  'Horyzont',
  'IKEA',
  'INDIGO',
  'IONITY',
  'In(n) Energie',
  'Inbalance',
  'Indelec',
  'Inselwerke',
  'Intermarché',
  'Interparking',
  'Izivia',
  'JOINON',
  'JOLT Energy',
  'JUCR CPO',
  'JUFI Group',
  'Joulz',
  'Jöchle Mobility',
  'KELAG',
  'KWMS',
  'Kaufland',
  'Kia',
  'Kommune',
  'Kostner',
  'LEW',
  'LSW',
  'LUBAY',
  'LUCHY',
  'LUDIE',
  "LUMI'iN",
  'Laadkracht',
  'Laadnet',
  'Laadpaal24',
  'Ladebusiness',
  'Ladegrün!',
  'Ladenetz',
  'Ladesonne',
  'Ladeverbund+',
  'Last Mile Solutions',
  'Leclerc',
  'Leikermoser Energiehandel',
  'Leisures',
  'Leitner Energy',
  'LichtBlick eMobility',
  'Lidl',
  'Liechtensteinische Kraftwerke',
  'Lightwell',
  'Losch Import',
  'Luminus',
  'MAHLE chargeBIG',
  'MAINGAU',
  'ME Energy',
  'MEISSENERSTADTWERKE',
  'MEYGO_CHARGE_GMBH',
  'MOL Plugee',
  'MOON',
  'MOVE',
  'MVM Mobiliti',
  'MVV Enamic',
  'MVV eMotion',
  'Mainova',
  'Mainzer Stadtwerke',
  'Maxem Energy',
  'MegaCharge',
  'Megatel',
  'Mennekes',
  'Mer',
  'Meygo Charge',
  'Migrol',
  'Migrol AG CPO',
  'Milepost',
  'Mobiflow',
  'MobileCharge',
  'Mobility Plus',
  'Mobility Pulse',
  'Mobilize Fast Charge',
  'MobilyGreen',
  'Modulo',
  'Modulo Energies',
  'Monta',
  'Moobi',
  'Métropole Nice Côte d’Azur',
  'Métropole du Grand Nancy',
  'NEW Niederrhein Energie und Wasser',
  'NL MAB',
  'NLABL',
  'NLALP',
  'NLBWT',
  'NLLEV',
  'NLLKS',
  'NLSGM',
  'NLcharge',
  'NONOXXPROFOLLOWER',
  'NRG Accounting',
  'NUMOBI',
  'NW IECharge',
  'NWGCHARGINGFOLLOWER',
  'NaturEnergie Community CH',
  'Neogy',
  'Neubrandenburger Wohnung',
  'Nexity',
  'Nissan',
  'Numbat',
  'OG Clean Fuels',
  'OK',
  'OK CPO',
  'OKQ8',
  'OMV eMotion',
  'OVAG Energie',
  'Olife Energy',
  'Opcharge',
  'Optiload',
  'Optimile',
  'Optimum Way',
  'Orlen',
  'Osterholzer Stadtwerke',
  'PCT',
  'PKP',
  'PLFEH',
  'PLWUA',
  'POSID Technologies',
  'PSA1',
  'Pariamus',
  'Park Charge',
  'Park&Charge',
  'Parkgaragengesellschaft Baden-Baden',
  'Parkl',
  'Parkraumgesellschaft Baden-Württemberg',
  'Parkstrom',
  'Partino CHF',
  'Petrol',
  'Pfalzwerke',
  'Plugfuse',
  'PluginCompany',
  'Pluginvest',
  'Polarstern',
  'Polenergia eMobility',
  'Polyfazer',
  'Porsche Sales & Marketplace',
  'Porsche Smart Mobility',
  'PowerDot',
  'PowerGo',
  'Powered By Zeno',
  'Powerland',
  'Powerstop',
  'Pražská energetika (PRE)',
  'Properphi',
  'Präg Energiedienstleistungen',
  'Q-Park',
  'Q.Ev. Solutions',
  'Q1 Autostrom',
  'Q8',
  'Q8 electric',
  'Qovoltis',
  'Qwello',
  'RSGNEUBRANDENBURG',
  'Recharge',
  'Renault',
  'Repower',
  'Retail',
  'Rheinenergie',
  'Road',
  'Robocharge',
  'Rossini Energy',
  'Route220',
  'SDEA 10',
  'SDED 52',
  'SDEY 89',
  'SEAK',
  'SEAPC',
  'SEMOB',
  'SGA Automation',
  'SIED 70',
  'SOCAR Charge',
  'SSE',
  'ST2B',
  'STADTWERKEAUEBADSCHLEMA',
  'STADTWERKEPEINE_FOLLOWER',
  'STADTWERKE_STEINBURG',
  'SUMIDA_FOLLOWER',
  'SWB',
  'SWIO',
  'SWK Energie',
  'SWM',
  'SWN Stadtwerke Neumünster',
  'SWNEUSTRELITZ',
  'SWT',
  'Saascharge',
  'SachsenEnergie',
  'SalzachSonne',
  'Schleswiger Stadtwerke',
  'Schneider Electric',
  'Scopius EV Charging',
  'Seijsener',
  'Sevdec',
  'Share Birrer',
  'Shell Recharge',
  'Siegener Versorgungsbetriebe',
  'Skoda',
  'Smappee',
  'Smart Fuel Pass',
  'Smartchargers X-Charge',
  'Smatrics',
  'Smatrics EnBW',
  'Smight',
  'Sminn',
  'Sodetrel-Corri-door',
  'Sonnenladen',
  'Spirii',
  'Spreewald Energy',
  'St. Josef-Stift Sendenhorst',
  'Stadtgemeinde Tulln an der Donau',
  'Stadtwerke Bad Säckingen',
  'Stadtwerke Bietigheim-Bissingen',
  'Stadtwerke Bochum',
  'Stadtwerke Bruchsal',
  'Stadtwerke Brunsbüttel',
  'Stadtwerke Buchholz i.d.N',
  'Stadtwerke Buxtehude',
  'Stadtwerke Bühl',
  'Stadtwerke Castrop-Rauxel',
  'Stadtwerke Dachau',
  'Stadtwerke Elbtal',
  'Stadtwerke Elmshorn',
  'Stadtwerke Ettlingen',
  'Stadtwerke Flensburg',
  'Stadtwerke Frankenthal',
  'Stadtwerke Görlitz',
  'Stadtwerke Göttingen',
  'Stadtwerke Güstrow',
  'Stadtwerke Hamm',
  'Stadtwerke Hartberg',
  'Stadtwerke Heidelberg',
  'Stadtwerke Heilbad Heiligenstadt',
  'Stadtwerke Heilbronn',
  'Stadtwerke Herne',
  'Stadtwerke Husum',
  'Stadtwerke Ingolstadt',
  'Stadtwerke Iserlohn',
  'Stadtwerke Kaarst',
  'Stadtwerke Kaiserslautern',
  'Stadtwerke Kerpen',
  'Stadtwerke Kiel',
  'Stadtwerke Klagenfurt',
  'Stadtwerke Kufstein',
  'Stadtwerke Leipzig',
  'Stadtwerke Lindau (B)',
  'Stadtwerke Ludwigsburg-Kornwestheim',
  'Stadtwerke Lübbecke',
  'Stadtwerke Lübeck',
  'Stadtwerke Lünen',
  'Stadtwerke Marburg',
  'Stadtwerke München',
  'Stadtwerke Neustrelitz',
  'Stadtwerke Norderstedt',
  'Stadtwerke Pforzheim',
  'Stadtwerke Potsdam',
  'Stadtwerke Rastatt',
  'Stadtwerke Rostock',
  'Stadtwerke Schwarzenberg',
  'Stadtwerke Solingen',
  'Stadtwerke Stade',
  'Stadtwerke Stuttgart',
  'Stadtwerke Troisdorf',
  'Stadtwerke Tübingen',
  'Stadtwerke Unna',
  'Stadtwerke Wedel',
  'Stadtwerke Weinheim',
  'Stadtwerke Weißenfels',
  'Stadtwerke Weißwasser',
  'Stadtwerke Winsen',
  'Stadtwerke Wismar',
  'Stadtwerke Witten',
  'Stadtwerke Zittau',
  'Stations-e',
  'StromSpeicherMarkt',
  'Stromquelle Energietechnik',
  'Stroohm',
  'Städtische Werke Magdeburg',
  'Swarco',
  'Swisscharge',
  'SÜLL',
  'SüwagAG &KG',
  'T-Electric',
  'TEA',
  'TEA MOBILITAS',
  'TEAG Mobil',
  'TECHNAGON_FOLLOWER',
  'TECHNAGON_OPERATIONS_FOLLOWER',
  'TIWAG',
  'TankE',
  'Tap Electric',
  'Taubert Consulting',
  'Tauron',
  'Technische Werke Naumburg',
  'Technische Werke Schussental',
  'Teplárny Brno',
  'Tesla',
  'Tesla Supercharger',
  'TotalEnergies',
  'Tulln Energie',
  'UGV Chargers',
  'Unterfränkische Überlandzentrale',
  'V-Markt',
  'VB Hann. Münden',
  'VB Hoyerswerda',
  'VKW Vlotte',
  'Van Leeuwen',
  'Vandebron',
  'Vattenfall',
  'Versorgungsservice Main-Kinzig GmbHBarbarossastraße 2663571 Gelnhausen',
  'Virta',
  'Volkswagen',
  'Voltiva',
  'Volvo Charging',
  'WAAT',
  'WEMAG',
  'WVV',
  'WWZ Energie',
  'Wattif Europe',
  'Wattify',
  'We Drive Solar',
  'Wels Strom',
  'Westfalen Weser Ladeservice',
  'Westfalen Weser Netz',
  'Wien Energie',
  'Wirelane',
  'Würth',
  'Würth Elektrogroßhandel',
  'YES55',
  'ZE-WATT',
  'ZEENCO e-mobility',
  'ZEborne',
  'ZSE Drive',
  'Zwickauer Energieversorgung',
  'avency',
  'badenova',
  'chargeIQ',
  'chargecloud',
  'da emobil',
  'deer',
  'drivee',
  'e-RS',
  'e-laden Tirol',
  'e-regio',
  'eCarUp',
  'eLoaded',
  'eeproperty',
  'eins energie',
  'ejoin',
  'ella',
  'emobil.link',
  'emonvia',
  'emosS',
  'emyon',
  'energielösung',
  'energis',
  'evensnelladen',
  'ews',
  'eze.network',
  'has.to.be',
  'iLumen',
  'NeutralPartner',
  'NeutralPartner Ceská republika',
  'NeutralPartner Energo',
  'kW-Solutions',
  'm8mit',
  'mw autostrom',
  'nonoxx pro',
  'novoeco | recharge (BayWa)',
  'smopi',
  'strommobil',
  'team eMobility',
  'ubitricity',
  'vaylens',
  'vaylens Applications - CPO',
  'vaylens GmbH - Austria',
  'ÖAMTC',
  'ČEZ',
];

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\ ]/g, '\\$&'); // $& means the whole matched string
}

export function makePattern(s: string): string {
  // every db entry is converted into regex pattern where special characters are optional
  let pattern = '';
  const specialCharsSet = new Set<string>([
    ' ',
    '.',
    ',',
    '/',
    '#',
    '!',
    '$',
    '%',
    '^',
    '&',
    '*',
    ';',
    ':',
    '{',
    '}',
    '=',
    '-',
    '_',
    '`',
    '~',
    '(',
    ')',
    '|',
  ]);
  for (const char of s) {
    if (specialCharsSet.has(char)) {
      pattern += escapeRegExp(char) + '?\\ ?';
    } else {
      pattern += escapeRegExp(char);
    }
  }
  return `\\b(${pattern})\\b`;
}

export type SUPPORTED_PEER_ID = 'FRK' | 'MUV' | 'TEST' | 'NeutralPartner';

let FRK_OPERATOR_NAMES_WITH_REGEX: RegExp[] = [];
let MUV_OPERATOR_NAMES_WITH_REGEX: RegExp[] = [];
let NeutralPartner_OPERATOR_NAMES_WITH_REGEX: RegExp[] = [];

export const getOperatorNames = (peerId: SUPPORTED_PEER_ID) => {
  if (peerId === 'FRK') {
    return OPERATOR_NAMES;
  }

  if (peerId === 'MUV') {
    return MUV_OPERATOR_NAMES;
  }

  if (peerId === 'NeutralPartner') {
    return NeutralPartner_OPERATOR_NAMES;
  }

  if (peerId === 'TEST') {
    return [...OPERATOR_NAMES, ...MUV_OPERATOR_NAMES, ...NeutralPartner_OPERATOR_NAMES];
  }

  throw new Error('Invalid peerId');
};

export const getOperatorNamesWithRegex = (peerId: SUPPORTED_PEER_ID) => {
  if (peerId === 'FRK') {
    if (FRK_OPERATOR_NAMES_WITH_REGEX.length < 1) {
      FRK_OPERATOR_NAMES_WITH_REGEX = OPERATOR_NAMES.map((operator) => {
        const pattern = makePattern(operator.toLowerCase());
        const regex = new RegExp(pattern, 'gi');
        return regex;
      });
    }

    return FRK_OPERATOR_NAMES_WITH_REGEX;
  }

  if (peerId === 'MUV') {
    if (MUV_OPERATOR_NAMES_WITH_REGEX.length < 1) {
      MUV_OPERATOR_NAMES_WITH_REGEX = MUV_OPERATOR_NAMES.map((operator) => {
        const pattern = makePattern(operator.toLowerCase());
        const regex = new RegExp(pattern, 'gi');
        return regex;
      });
    }

    return MUV_OPERATOR_NAMES_WITH_REGEX;
  }

  if (peerId === 'NeutralPartner') {
    if (NeutralPartner_OPERATOR_NAMES.length < 1) {
      NeutralPartner_OPERATOR_NAMES_WITH_REGEX = NeutralPartner_OPERATOR_NAMES.map(
        (operator) => {
          const pattern = makePattern(operator.toLowerCase());
          const regex = new RegExp(pattern, 'gi');
          return regex;
        }
      );
    }

    return MUV_OPERATOR_NAMES_WITH_REGEX;
  }

  if (peerId === 'TEST') {
    getOperatorNamesWithRegex('FRK');
    getOperatorNamesWithRegex('MUV');
    getOperatorNamesWithRegex('NeutralPartner');

    return [...FRK_OPERATOR_NAMES_WITH_REGEX, ...MUV_OPERATOR_NAMES_WITH_REGEX];
  }

  throw new Error('Invalid peerId');
};

