export {
  InvalidRequestParameterError,
  DuplicatedEvseError,
  DuplicatedLocationError,
  NoPredictionInCacheError,
  PredictionInCacheExpiredError,
  ForbiddenRequestError,
  UnknownEntityError,
  InternalServerError,
  UnprocessedRequestError,
  UnsupportedAudioFormatError,
  InvalidAddressRequestError,
  InvalidDateTimeRequestError,
  NoChargePointsAvailableError,
  NoChargePointsInDBError,
  ChargeGPTInternalServerError,
  ChargeGPTInvalidRequestParameterError,
  ChargeGPTForbiddenRequestError,
  RecommendationInternalServerError,
  RecommendationForbiddenRequestError,
  ChargeGPTUnauthorizedRequestError,
  isExpectedError,
} from './expected-errors';